name: ecommerce_app_ui_kit
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  flutter_svg: ^0.18.0
  flutter_staggered_grid_view: ^0.3.0
  sticky_headers: ^0.1.8
  datetime_picker_formfield: ^0.4.2
  curved_navigation_bar: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/onboarding0.png
    - img/onboarding1.png
    - img/onboarding2.png
    - img/onboarding3.png
    - img/twitter.png
    - img/facebook.png
    - img/google-plus.png
    - img/linkedin.png
    - img/user1.jpg
    - img/user2.jpg
    - img/user3.jpg
    - img/user0.jpg
    - img/visa.png
    - img/paypal.png
    - img/apple_pay.png
    - img/brazil.png
    - img/canada.png
    - img/china.png
    - img/france.png
    - img/germany.png
    - img/italy.png
    - img/netherlands.png
    - img/spain.png
    - img/united-arab-emirates.png
    - img/united-states-of-america.png
    - img/marker.png
    - img/pro1.webp
    - img/pro2.webp
    - img/pro3.webp
    - img/pro4.webp
    - img/pro5.webp
    - img/pro6.webp
    - img/pro7.webp
    - img/man1.webp
    - img/man2.webp
    - img/man3.webp
    - img/man4.webp
    - img/man5.webp
    - img/man6.webp
    - img/man7.webp
    - img/man8.webp
    - img/baby1.webp
    - img/baby2.webp
    - img/baby3.webp
    - img/baby4.webp
    - img/baby5.webp
    - img/baby6.webp
    - img/home1.webp
    - img/home2.webp
    - img/home3.webp
    - img/home4.webp
    - img/home5.webp
    - img/home6.webp
    - img/home7.webp
    - img/home8.webp
    - img/home9.webp
    - img/home10.webp
    - img/home11.webp
    - img/sport1.webp
    - img/sport2.webp
    - img/sport3.webp
    - img/sport4.webp
    - img/sport5.webp
    - img/sport6.webp
    - img/sport7.webp
    - img/sport8.webp
    - img/sport9.webp
    - img/sport10.webp
    - img/watch1.webp
    - img/watch2.webp
    - img/watch3.webp
    - img/watch4.webp
    - img/watch5.webp
    - img/watch6.webp
    - img/watch7.webp
    - img/watch8.webp
    - img/watch9.webp
    - img/acer.svg
    - img/apple.svg
    - img/casio.svg
    - img/samsung.svg
    - img/xerox.svg
    - img/nikon.svg
    - img/intel.svg
    - img/huawei.svg
    - img/gopro.svg
    - img/hp.svg
    - img/logo-03.svg
    - img/logo-04.svg
    - img/logo-05.svg
    - img/logo-06.svg
    - img/logo-07.svg
    - img/logo-08.svg
    - img/logo-09.svg
    - img/logo-10.svg
    - img/logo-11.svg
    - img/slider1.jpg
    - img/slider2.jpg
    - img/slider3.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family:  EcommerceAppUI
     fonts:
      - asset: fonts/EcommerceAppUI.ttf
   - family: Poppins
     fonts:
       - asset: fonts/Poppins-Thin.ttf
         weight: 100
       - asset: fonts/Poppins-ExtraLight.ttf
         weight: 200
       - asset: fonts/Poppins-Light.ttf
         weight: 300
       - asset: fonts/Poppins-Regular.ttf
         weight: 400
       - asset: fonts/Poppins-Medium.ttf
         weight: 500
       - asset: fonts/Poppins-SemiBold.ttf
         weight: 600
       - asset: fonts/Poppins-Bold.ttf
         weight: 700
       - asset: fonts/Poppins-ExtraBold.ttf
         weight: 800
       - asset: fonts/Poppins-Black.ttf
         weight: 900
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
